backpressure = 1000
reqs_per_client = 10
execution = 'Threadpool'

[authentication]
peers = "Ed25519"

[batch]
min = 1
max = 1

[batch.timeout]
secs = 0
nanos = 100_000_000

[[peers]]
id = 0
host = '127.0.0.1'
bind = '127.0.0.1'
client_port = 10002
peer_port = 10003
prometheus_port = 10004
private_key = "keys/ed-25519-private-0"
public_key = "keys/ed-25519-public-0"

[[peers]]
id = 1
host = '127.0.0.1'
bind = '127.0.0.1'
client_port = 20102
peer_port = 20103
prometheus_port = 10104
private_key = "keys/ed-25519-private-1"
public_key = "keys/ed-25519-public-1"

[[peers]]
id = 2
host = '127.0.0.1'
bind = '127.0.0.1'
client_port = 10202
peer_port = 10203
prometheus_port = 10204
private_key = "keys/ed-25519-private-2"
public_key = "keys/ed-25519-public-2"

[[peers]]
id = 3
host = '127.0.0.1'
bind = '127.0.0.1'
client_port = 10302
peer_port = 10303
prometheus_port = 10304
private_key = "keys/ed-25519-private-3"
public_key = "keys/ed-25519-public-3"
