id = 0
backpressure = 1000
reqs_per_client = 10
execution = 'Single'

[authentication]
peers = "Ed25519"

[batch]
min = 1
max = 1

[batch.timeout]
secs = 0
nanos = 100_000_000

[[peers]]
id = 0
host = '172.16.32.1'
client_port = 10002
peer_port = 10003
prometheus_port = 10004
private_key = "keys/ed-25519-private-0"
public_key = "keys/ed-25519-public-0"

[[peers]]
id = 1
host = '172.16.32.2'
client_port = 10002
peer_port = 10003
prometheus_port = 10004
private_key = "keys/ed-25519-private-1"
public_key = "keys/ed-25519-public-1"

[[peers]]
id = 2
host = '172.16.32.3'
client_port = 10002
peer_port = 10003
prometheus_port = 10004
private_key = "keys/ed-25519-private-2"
public_key = "keys/ed-25519-public-2"

[[peers]]
id = 3
host = '172.16.32.4'
client_port = 10002
peer_port = 10003
prometheus_port = 10004
private_key = "keys/ed-25519-private-3"
public_key = "keys/ed-25519-public-3"
